FROM node:22.14.0-alpine3.21 As builder

WORKDIR /app

COPY . .

RUN npm install 

RUN npm run build

FROM gcr.io/distroless/nodejs22-debian12

WORKDIR /app

###COPY --from=builder /app/build /app/build

COPY --from=builder /app .

EXPOSE 3000

CMD ["npm","run","dev"]
